# on my macbook pro only 'h', 'l', 'w', 'x' are reserved
alias s='gs'
alias a='ga'
alias c='gc'
alias u='gull'
alias p='gush'
alias g='gl'
alias b='gb'
alias o='gco'
alias d='gd'
alias d1='gd1'
alias d2='gd2'
